### ISSUE TITLE
After closing a workspace, the name of project/workspace is still output in the status bar

### ISSUE THREAD

**Issue by tukusejssirs** [Val95240/ProjectManager#1]
I’d expect that when I close a currently open workspace using `close_workspace` command (or `Project` → `Close Project`), `[project_name/workspace_name]` would be removed from there or at least some arbitrary string (like `n/a` or `no project open`) would be output. I’d prefer the first option though (output nothing), as it is how it works when no project was open in the current window yet.

**Comment by tukusejssirs** [comment]
> Is this also the behavior you observe, or am I missing something ?

Yes.

---

Before you implemented this feature, I used [this code](https://gitlab.com/tukusejssirs/lnx_scripts/-/blob/master/subl_packages/project_name_in_status_bar.py) to output the project name in status bar. Look at [L35-36](https://gitlab.com/tukusejssirs/lnx_scripts/-/blob/master/subl_packages/project_name_in_status_bar.py#L35-36), which works even  in this case as I think should output project name only when a project is loaded.

**Comment by Val95240** [comment]
What's weird is that I use exactly the same code !
If you look at [the plugin code](https://github.com/Val95240/ProjectManager/blob/536a633ba8d537a2b7e705677bac52b02837023f/project_manager.py#L166-L213), I'm calling exactly the same methods, so I'm really not sure what could be the difference between the two behaviors.

**Comment by tukusejssirs** [comment]
Unfortunately, the change didn’t fix the issue.

I have just double-checked that my plugin updates status bar immediately after I close the project/workspace, while PM updates it only after I either:
- select another window and reselect the window where I closed the project;
- open and close any overlay (like Commands Pallete or PM’s overlay of commands).

However, It immediately appears when I open a project.

---

Could the order be important? Or something else?

**Comment by Val95240** [comment]
That's really weird.
I'm not really sure what to tell you here, I don't think the plugin is doing anything different, and on my computer the status message disappears immediately when closing the project, so I don't know what could cause the issue in your case, sorry...
Maybe Sublime doesn't update in some specific cases, but I am not sure there's a way for us to tell if that is the case.

**Comment by tukusejssirs** [comment]
> Maybe Sublime doesn't update in some specific cases, but I am not sure there's a way for us to tell if that is the case.

Yeah, so I think too. You see, my code is quite simple, while PM contains much more code (for other features), that’s why I talked about the order. Maybe if we move updating the status panel to top of the functions and/or conditions, it might fix it.

I’ll try 5o find some time and test this out.

---

> on my computer the status message disappears immediately when closing the project

Well, maybe your computer (DE/WM) behaves differently to Sway. Could you share with me your OS/distro version please? I’d like to test my ST config (incl plugins etc) on OS you use. Thanks! :pray:
