### ISSUE TITLE
 Add an option to move a workspace to another project

### ISSUE THREAD

**Issue by tukusejssirs** [Val95240/ProjectManager#10]
Additionally to #9, it might be nice to move a workspace to another project (with custom workspace name supplied by user).

**Comment by Val95240** [comment]
In my opinions, projects should be quite independent, usually working in completely different folders on distinct files.
Even in the unusual case where several projects were to contain the same files, workspaces should still be logically linked to a project, and I don't think it really makes sense to transfer workspaces between projects.
