### ISSUE TITLE
When a workspace contains a slash on Linux, it errors out that it contains a backslash

### ISSUE THREAD

**Issue by tukusejssirs** [Val95240/ProjectManager#13]
I use Linux. I have just tried out if we can create a workspace in a subfolder of a project (e.g. `subfolder/workspace_name`). It greeted me with the following error.

https://github.com/Val95240/ProjectManager/blob/c9f1b58337ffe3d174e1440d6a8a706ab64d640f/project_manager.py#L987

While it might be a nice feature to allow subfolders in projects for workspaces, this error is incorrect on Linux/macOS, as on these platforms, we use slashes (`/`) to separate folders in paths.

I think it could be fixed using this:

```python
if sublime.platform() == 'windows':
    sublime.message_dialog("Invalid name: can't contain a '\\'")
else:
    sublime.message_dialog("Invalid name: can't contain a '/'")
return
```

Do you think I could create a PR for this or you need to do something else too in order to fix this issue.

**Comment by Val95240** [comment]
For the plugin to work, the workspace files have to be in the same folder as the project file, so it's not possible to create workspaces in subfolder.

You're right concerning the error message though, I've fixed it, it should be good on all platforms now.
