### ISSUE TITLE
`Append Project` does not seem to work

### ISSUE THREAD

**Issue by tukusejssirs** [Val95240/ProjectManager#15]
I presumed that `Append Project` would append all files (both saved and unsaved), and other state information from a selected workspace to currectly open workspace.

However, it does not seem to do anything. Moreover, when I select a project with more than one workspace to be appended to currently open workspace, it does not prompt me to choose one of the workspaces.

**Comment by Val95240** [comment]
The `Append Project` command simply adds all the folders opened in a project to the current window (same thing as executing `Add Folder to Project` for each of the folders).
I did not modify it from the original plugin, but I agree that it is not the most useful command right now, and the name is a bit confusing.

I think what you propose would indeed be better, but unfortunately there's no way to achieve that in Sublime Text, or at least not easily, I already tried previously, but with no luck so far.
I'm gonna keep looking in the future, and I'll update the plugin if I manage to solve this.
