### ISSUE TITLE
Add workspace description

### ISSUE THREAD

**Issue by tukusejssirs** [Val95240/ProjectManager#16]
I use many workspaces (more than 100). I use some workspaces (nearly) every day, others are much more rarely used.

Therefore I suggest to implement a feature to describe each and every workspace. We could also describe the project itselft, however, that is of less importance to me.

Now, we cannot use `.sublime-workspace` files, as those are overwritten whenever ST writes its content into that file.

We could use `.sublime-project` files, which accept unknown keys and values. However, I think that using `recent.json` would be much better.

`recent.json` could contain something like this:

```json
[
  {
    "project": "~/.config/sublime-text/Packages/User/Projects/some_project/some_project.sublime-project",
    "description": "Project description",
    "workspaces":
    [
      {
        "name": "/home/ts/.config/sublime-text/Packages/User/Projects/some_project/some_project.sublime-workspace",
        "description": "Workspace description"
      }
    ]
  }
]
```

The description (when available) could be then used in the workspace list instead of open files. When the particular workspace does not have description set, open files should be listed as it is the case now.

Similarly, the project description (when available) could be used in the project list instead of the first project folder.

**Comment by Val95240** [comment]
That's a good idea, I agree that it could really be useful !
I tried something and updated the plugin, tell me if that's what you had in mind and if you find any bug !
