### ISSUE TITLE
Sometimes the project/workspace name disappears from the status bar

### ISSUE THREAD

**Issue by tukusejssirs** [Val95240/ProjectManager#4]
Related: #1

---

I have usually open multiple windows (some with open projects, others without any project) and I don’t close all the windows prior to quitting ST (I let ST to re-open them on its next startup).

Now, the issue is that sometimes the project/workspace name disappears from the status bar. It does not matter if the project was reopen by ST on startup or it was open at ST runtime. Re-opening the project puts the project/workspace name back into the status bar.

**Comment by Val95240** [comment]
Once again, I couldn't reproduce this issue. On my computer, the status bar updates as soon as the plugin is loaded, so it technically can't be faster than that.
I'm not sure why this is not the case in your setup.
I still modified the code to force update on sublime start-up, can you tell me if it fixes the issue for you ?
Thanks !

**Comment by tukusejssirs** [comment]
Maybe I was not clear enough. Here are reproduction steps:

1. Open an existing project. The status bar contains the current project name.
2. Close the project (`Project` → `Close Project`). The status bar still contains the project name which we last closed until either:
  - the window is closed;
  - a another project is opened/created;
  - [new] another window is selected AND the window where the project was open is reselected.

I also noticed that on ST startup, project/workspace names are not present in the status bar when the projects/workspaces are left open when I quit ST.

**Comment by Val95240** [comment]
Ah okay, I see what you mean ! It seems to be basically the same issue as in #1 then, and I think the commit I made will fix it.
