### ISSUE TITLE
Add commands that work with currently open project/workspace

### ISSUE THREAD

**Issue by tukusejssirs** [Val95240/ProjectManager#6]
When a project/workspace is open in current window, we could have the following commands for current project/workspace (currently, we need to select a project/workspace prior to executing the particular command):
- edit project;
- rename project.

Of course, when no project/workspace is open in current window, these commands should ideally be omitted or at least made unselectable.

**Comment by Val95240** [comment]
I actually prefer the current behavior, I usually rename projects even when they're not open.
This allows me to rename or edit a bunch of projects at a time, which I find more convenient to reorganize my projects.
Moreover, this only adds one key press, which is acceptable in my opinion.
