### ISSUE TITLE
Add an number of workspaces indicator to project list

### ISSUE THREAD

**Issue by tukusejssirs** [Val95240/ProjectManager#7]
Currently, there is no way to know how many workspaces are associated with a particular project.

It might be a good idea to add an indicator of how many workspaces are in a project. It might be as simple as a number in a circle, ideally with a tooltip saying something like `Number of workspaces in the project`.

Of course, it might be a good idea to output it only when there are two or more workspaces associated with particular project.

**Comment by Val95240** [comment]
I added it as an annotation in the project list, tell me if you find any issue with it !
