### ISSUE TITLE
Add an option to move a project

### ISSUE THREAD

**Issue by tukusejssirs** [Val95240/ProjectManager#9]
We already have an option to rename a project (change its name only), we I recently wanted to tidy up my projects, so I wanted to move a project from one folder to another, e.g. moving a project from `proj1/proj1/proj1.sublime-{project,workspace}` to `company/proj1/proj1.sublime-{project,workspace}`.

I think this operation should be separate from renaming a project (unlike `mv` command in terminal).

As a workaround, I was able to make it work by simply moving the project folder to a new place (e.g. `mv proj1/proj1 company`) and run `Refresh Projects` command.

**Comment by Val95240** [comment]
Are you talking about projects imported using the `Import Project` command or about project files in the default project path `PATH/TO/Packages/Users/Projects` ?
For projects in the default path, they should not have to be moved by hand as renaming a project is equivalent to moving these files.
For projects with `.sublime-project` and `.sublime-workspace` files stored directly in the development directories and imported through `Import Project`, I feel like this is not the role of this plugin to move the whole directory to another location.
ProjectManager should only deal with sublime files, and should not modify other files or directories as it could easily delete or alter important files if not careful.

I agree that right now moving a folder containing a sublime project is not very practical, but I don't see a way to achieve it without having to modify regular files, so I won't get into that.
I might add a function to update paths of projects that the plugin can't find anymore to simplify the process though.
